version: "3.9"

services:
  crawl:
    build: .
    container_name: ss-crawl
    volumes:
      - ./../data/papers:/app/data/papers
      - ./../results:/app/results
    environment:
      MAX_PAPERS: ${MAX_PAPERS}
      MIN_WAIT_TIME: ${MIN_WAIT_TIME}
      MAX_WAIT_TIME: ${MAX_WAIT_TIME}

  cache:
    image: redis:alpine
    container_name: ss-cache
    volumes:
      - ./../data/redis:/data
