version: '3.9'

services:
  ui:
    build: streamlit
    ports:
      - "8501:8501"

  backend:
    build: backend
    environment:
      PORT: 50051
      NUM_WORKERS: 8
      PYTHONUNBUFFERED: 1
    volumes:
      - ./../data/:/data
      - ./../results/:/results
      - ./../drive/:/drive
      - ./nltk_data/:/root/nltk_data
      - ./cache:/root/cache
